# Generated by Django 4.1.6 on 2023-02-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=200, null=True, verbose_name='Картина')),
                ('date', models.CharField(max_length=100, null=True, verbose_name='Дата')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Цена')),
                ('currency', models.CharField(max_length=100, null=True, verbose_name='Валюта')),
            ],
        ),
    ]
